### ISSUE TITLE
Incorrect java edition

### ISSUE THREAD

**Issue by dturk0610** [PrismarineJS/minecraft-chunk-dumper#32]
Hi, I am new to the Minecraft api/bot/chunk viewing community. I am trying to generate a chunk using the command that you instructed in you install/example use process, but the I run the blow command I get a "java too old error".

      > minecraftChunkDumper saveChunks 1.19 "1_19" 10

      Java too old, have java for class files version 61.0, need java for class files version 55.0

It spits out a little more than this obviously but this is what the issue is I believe. I am running this on a MacBook pro with an M1 chip. When I run several java version control commands I get this output:

     > /usr/libexec/java_home -V                           

     Matching Java Virtual Machines (4):
         11.0.16 (arm64) "Oracle Corporation" - "Java SE 11.0.16" /Library/Java/JavaVirtualMachines/jdk-11.0.16.jdk/Contents/Home
         11.0.12 (x86_64) "Eclipse Temurin" - "Eclipse Temurin 11" /Library/Java/JavaVirtualMachines/temurin-11.jdk/Contents/Home
         1.8.341.10 (x86_64) "Oracle Corporation" - "Java" /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home
         1.8.0_301 (x86_64) "Oracle Corporation" - "Java SE 8" /Library/Java/JavaVirtualMachines/jdk1.8.0_301.jdk/Contents/Home
     /Library/Java/JavaVirtualMachines/jdk-11.0.16.jdk/Contents/Home

When researching the issue it seemed like I just needed to set my java edition to the prompted 55 java version which seemed to be the 11.0.16 that I have installed, so I ran:

     > export JAVA_HOME=`/usr/libexec/java_home -v 11.0.16` 

Then tested it with java and java version checking:

     > java -version                                       
          java version "11.0.16" 2022-07-19 LTS
          Java(TM) SE Runtime Environment 18.9 (build 11.0.16+11-LTS-199)
          Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.16+11-LTS-199, mixed mode)
     > javac -version
          javac 11.0.16

I'm sorry if this is the wrong place to ask for help, I have no idea what could be wrong as oracle's website indicates that the java version I'm using is the desired 55 version.

**Comment by rom1504** [comment]
you need java 17

**Comment by dturk0610** [comment]
Oh alright. I tried that out and that seems to work! Thank you! I guess my confusion came from it saying I needed java for class files 55. Thank you for the quick reply!
