### ISSUE TITLE
Add more docs or examples.

### ISSUE THREAD

**Issue by allbombson** [PrismarineJS/minecraft-chunk-dumper#6]
Can you guys maybe add some more detail. For example u say .start needs node-minecraft-protocol but nothing related to it is in the example.

**Comment by roblabla** [comment]
What are you trying to achieve? minecraft-chunk-dumper downloads the official server JAR, creates a server, connects to it, and dumps the chunks. It's meant to be used as a debugging tool. You shouldn't have to worry about the node-minecraft-protocol part at all, it's all handled internally by the library.

**Comment by rom1504** [comment]
Indeed
